In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
a.shape

(2, 7)

In [4]:
# Get specific element [r, c] 
# r = row index
# c = column index
a[1, 5] # Remember the rows start at 0

13

In [5]:
# Get a specific row
a[0, :] # ':' accesses everything in the row

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [7]:
# Getting more complex indexes [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [9]:
a[0, 1:-1:2]  # -1 is going backwards at the end of array

array([2, 4, 6])

In [10]:
# Change an element in the array
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [11]:
# Change an entire series of numbers at index of 2 of each array
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [12]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [13]:
# 3D Array Example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
# Get a specific element (work outside in)
b[0,1,1] # 4

4

In [15]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [17]:
# Replace
b[:,1,:] = [[9,9],[8,8]]

In [18]:
b

array([[[9, 9],
        [9, 9]],

       [[5, 6],
        [8, 8]]])