In [1]:
import numpy as np
#Built in function for numpy to use

In [2]:
# All 0s matrix 2D
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# All 0s matrix 3D
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
# All 0s matrix 4D
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [5]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [6]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [7]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [8]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [9]:
np.full((2,2), 99, dtype='float')

array([[99., 99.],
       [99., 99.]])

In [10]:
# Any other number (full_like)
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [11]:
# Other alternative besides using full
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
np.full(c.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [12]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.8594985 , 0.32737422],
       [0.72069449, 0.17805188],
       [0.37804764, 0.83549602],
       [0.66432826, 0.61427138]])

In [13]:
np.random.rand(4,2,3)

array([[[0.00750877, 0.82578115, 0.15656463],
        [0.88694092, 0.32758667, 0.52638369]],

       [[0.26591114, 0.73678595, 0.57675171],
        [0.4364394 , 0.64200019, 0.19490681]],

       [[0.6815993 , 0.56346525, 0.43617087],
        [0.44253434, 0.78777672, 0.30244808]],

       [[0.36673013, 0.73438488, 0.50430936],
        [0.7354467 , 0.4333527 , 0.04610604]]])

In [14]:
# Random numbers using shape sample
np.random.random_sample(a.shape)

array([[0.90803457, 0.79318496, 0.07422147, 0.41983918, 0.52030543,
        0.63729446, 0.40547768],
       [0.64008103, 0.69333767, 0.04345794, 0.52744044, 0.45979375,
        0.32482339, 0.916667  ]])

In [15]:
# Random integer values
np.random.randint(7, size=(3,3)) # 3 X 3 for array size

array([[1, 2, 3],
       [3, 1, 2],
       [5, 6, 4]])

In [16]:
np.random.randint(4,7, size=(3,3)) # 3 X 3 for array size between 4 and 7 number only

array([[4, 6, 4],
       [4, 5, 5],
       [4, 4, 5]])

In [17]:
np.random.randint(-4,7, size=(3,3)) # 3 X 3 for array size between -4 and 7 number only

array([[-3,  0,  4],
       [-3, -2,  4],
       [ 5,  4,  5]])

In [18]:
# Identity matrix is a square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Identity matrix is a square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# Repeat an array multiple times
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [21]:
# Repeat an array multiple times and specifiying an axis using a 2D array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
# Repeat an array multiple times and specifiying an axis using a 2D array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [23]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays

In [24]:
a = np.array([1,2,3])
#b = a
#Use a.copy instead
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


#### Mathematics

In [25]:
d = np.array([1,2,3,4])

In [26]:
d + 2

array([3, 4, 5, 6])

In [27]:
d += 2
d

array([3, 4, 5, 6])

In [28]:
d - 2

array([1, 2, 3, 4])

In [29]:
d * 2

array([ 6,  8, 10, 12])

In [30]:
d / 2

array([1.5, 2. , 2.5, 3. ])

In [31]:
e = np.array([1,0,1,0])
d + e

array([4, 4, 6, 6])

In [32]:
d ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [33]:
# Take the sin 
np.sin(d)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [34]:
#Take the cos
np.cos(d)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [35]:
## https://docs.scipy.org/doc/numpy/reference/routines.math.html

### Linear Algebra

In [36]:
a1 = np.ones((2,3)) # 2 X 3 Matrix of ones
print(a1)

b1 = np.full((3,2), 2)
b1

[[1. 1. 1.]
 [1. 1. 1.]]


array([[2, 2],
       [2, 2],
       [2, 2]])

In [37]:
# Matrix multiply functuion
np.matmul(a1,b1)

array([[6., 6.],
       [6., 6.]])

In [38]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [39]:
# Reference doc (https:// docs.scipy.org/numpy/reference/routines.linalg.html)
# Determinant
# Trace
# Eigenvalues
# Matrix Norm
# Inverse
# Etc
