In [1]:
import numpy as np
#Built in function for numpy to use

In [2]:
# All 0s matrix 2D
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# All 0s matrix 3D
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
# All 0s matrix 4D
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [5]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [6]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [7]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [8]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [9]:
np.full((2,2), 99, dtype='float')

array([[99., 99.],
       [99., 99.]])

In [10]:
# Any other number (full_like)
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [11]:
# Other alternative besides using full
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
np.full(c.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [12]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.17191572, 0.54335104],
       [0.79169546, 0.34575557],
       [0.23605676, 0.30385071],
       [0.32419402, 0.29073022]])

In [13]:
np.random.rand(4,2,3)

array([[[0.28273735, 0.05646843, 0.47773501],
        [0.35812315, 0.43277815, 0.26900007]],

       [[0.06637732, 0.97254875, 0.34177393],
        [0.5366372 , 0.77940635, 0.32149367]],

       [[0.83336754, 0.33580741, 0.88846464],
        [0.86357044, 0.32281131, 0.69547814]],

       [[0.36492337, 0.73430298, 0.21905312],
        [0.82154282, 0.16187249, 0.19264578]]])

In [14]:
# Random numbers using shape sample
np.random.random_sample(a.shape)

array([[0.77344164, 0.43802674, 0.17592566, 0.81357213, 0.42342907,
        0.0981217 , 0.75716192],
       [0.82060009, 0.89142289, 0.51764627, 0.52093154, 0.0374655 ,
        0.70159758, 0.23327439]])

In [15]:
# Random integer values
np.random.randint(7, size=(3,3)) # 3 X 3 for array size

array([[4, 2, 4],
       [5, 0, 5],
       [6, 5, 0]])

In [16]:
np.random.randint(4,7, size=(3,3)) # 3 X 3 for array size between 4 and 7 number only

array([[6, 6, 6],
       [4, 5, 4],
       [4, 6, 5]])

In [17]:
np.random.randint(-4,7, size=(3,3)) # 3 X 3 for array size between -4 and 7 number only

array([[ 1,  0,  4],
       [-2,  4, -3],
       [ 5,  4, -2]])

In [18]:
# Identity matrix is a square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Identity matrix is a square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# Repeat an array multiple times
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [21]:
# Repeat an array multiple times and specifiying an axis using a 2D array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
# Repeat an array multiple times and specifiying an axis using a 2D array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [23]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays

In [24]:
a = np.array([1,2,3])
#b = a
#Use a.copy instead
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


#### Mathematics

In [25]:
d = np.array([1,2,3,4])

In [26]:
d + 2

array([3, 4, 5, 6])

In [27]:
d += 2
d

array([3, 4, 5, 6])

In [28]:
d - 2

array([1, 2, 3, 4])

In [29]:
d * 2

array([ 6,  8, 10, 12])

In [30]:
d / 2

array([1.5, 2. , 2.5, 3. ])

In [31]:
e = np.array([1,0,1,0])
d + e

array([4, 4, 6, 6])

In [32]:
d ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [33]:
# Take the sin 
np.sin(d)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [35]:
#Take the cos
np.cos(d)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [36]:
## https://docs.scipy.org/doc/numpy/reference/routines.math.html

### Linear Algebra