In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Ger Dimension
a. ndim

1

In [5]:
# Get Shape if a and b together 2 x 3
a.shape 
b.shape 

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
a = np.array([1,2,3], dtype='int')
print(a)

[1 2 3]


In [8]:
#Get size
a.itemsize # 4
print(a.itemsize)
b.itemsize # 8
print(b.itemsize)

4
8


In [9]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [10]:
a.dtype

dtype('int16')

In [11]:
# Get size and itemsize
a.size
print(a.size) # 3
a.itemsize # 2

3


2

In [12]:
#Get total size 
a.size * a.itemsize # 6
print(a.nbytes) # 6

6
